// GENERATED by tools/bake-lights.py — do not edit by hand.
// Light sources read out of the painted courtyard plate. `u`/`v` are normalised
// plate coordinates; the engine maps them through the same transform it uses to
// draw the plate, so a light always sits on the flame that was painted for it.
// `radius` is in world pixels (the map is 1056 x 864).

import type { BakedLight } from '../game/Lighting';

export const COURTYARD_LIGHTS: BakedLight[] = [
  { u: 0.873, v: 0.4173, radius: 165, color: [255, 188, 112], intensity: 1.0, flicker: 0.34, kind: 'candle' },
  { u: 0.8789, v: 0.5012, radius: 165, color: [255, 188, 112], intensity: 1.0, flicker: 0.34, kind: 'candle' },
  { u: 0.6563, v: 0.4538, radius: 165, color: [255, 188, 112], intensity: 1.0, flicker: 0.34, kind: 'candle' },
  { u: 0.3241, v: 0.4537, radius: 165, color: [255, 188, 112], intensity: 1.0, flicker: 0.34, kind: 'candle' },
  { u: 0.1116, v: 0.5378, radius: 165, color: [255, 188, 112], intensity: 1.0, flicker: 0.34, kind: 'candle' },
  { u: 0.2767, v: 0.7578, radius: 165, color: [255, 188, 112], intensity: 1.0, flicker: 0.34, kind: 'candle' },
  { u: 0.5311, v: 0.2926, radius: 165, color: [255, 188, 112], intensity: 1.0, flicker: 0.34, kind: 'candle' },
  { u: 0.5954, v: 0.2191, radius: 165, color: [255, 188, 112], intensity: 1.0, flicker: 0.34, kind: 'candle' },
  { u: 0.4522, v: 0.2922, radius: 165, color: [255, 188, 112], intensity: 1.0, flicker: 0.34, kind: 'candle' },
  { u: 0.1597, v: 0.3064, radius: 165, color: [255, 188, 112], intensity: 1.0, flicker: 0.34, kind: 'candle' },
  { u: 0.386, v: 0.2189, radius: 165, color: [255, 188, 112], intensity: 1.0, flicker: 0.34, kind: 'candle' },
  { u: 0.1347, v: 0.8628, radius: 165, color: [255, 188, 112], intensity: 1.0, flicker: 0.34, kind: 'candle' },
  { u: 0.7, v: 0.8913, radius: 165, color: [255, 188, 112], intensity: 0.885, flicker: 0.34, kind: 'candle' },
  { u: 0.645, v: 0.6485, radius: 165, color: [255, 188, 112], intensity: 0.85, flicker: 0.34, kind: 'candle' },
  { u: 0.3321, v: 0.6485, radius: 165, color: [255, 188, 112], intensity: 0.809, flicker: 0.34, kind: 'candle' },
  { u: 0.7455, v: 0.1239, radius: 165, color: [255, 188, 112], intensity: 0.726, flicker: 0.34, kind: 'candle' },
  { u: 0.8218, v: 0.1238, radius: 165, color: [255, 188, 112], intensity: 0.721, flicker: 0.34, kind: 'candle' },
  { u: 0.7713, v: 0.1589, radius: 165, color: [255, 188, 112], intensity: 0.721, flicker: 0.34, kind: 'candle' },
  { u: 0.3744, v: 0.5382, radius: 165, color: [255, 188, 112], intensity: 0.721, flicker: 0.34, kind: 'candle' },
  { u: 0.7969, v: 0.1485, radius: 165, color: [255, 188, 112], intensity: 0.703, flicker: 0.34, kind: 'candle' },
  { u: 0.9129, v: 0.6512, radius: 165, color: [255, 188, 112], intensity: 0.703, flicker: 0.34, kind: 'candle' },
  { u: 0.2497, v: 0.241, radius: 250, color: [172, 92, 255], intensity: 0.85, flicker: 0.13, kind: 'rift' },
  { u: 0.0815, v: 0.2655, radius: 250, color: [172, 92, 255], intensity: 0.85, flicker: 0.13, kind: 'rift' },
  { u: 0.8996, v: 0.1863, radius: 250, color: [172, 92, 255], intensity: 0.85, flicker: 0.13, kind: 'rift' },
  { u: 0.1391, v: 0.3573, radius: 250, color: [172, 92, 255], intensity: 0.85, flicker: 0.13, kind: 'rift' },
  { u: 0.5, v: 0.335, radius: 330, color: [126, 168, 255], intensity: 0.85, flicker: 0.07, kind: 'fountain' },
];
