#!/usr/bin/env python3
"""
Candy in Wonderland — light baker.

Level 1 is painted: the courtyard plate already has candle flames, a violet rift
and a glowing fountain drawn into it. The tile map's candle tiles (type 6) are at
completely different coordinates, so lighting the level from tile data would put
pools of light where the art has none.

So we read the light positions out of the art itself. This finds the painted
flames and the rift burst, merges overlapping hits into single sources, and emits
them as normalised plate coordinates. The engine maps those through the same
transform it uses to draw the plate, so the lights stay pinned to the painted
flames even if the plate's anchor changes.

This is a bake step, not a runtime cost — it runs here, once.

    python tools/bake-lights.py      ->  src/data/courtyard-lights.ts
"""
import os
import numpy as np
from PIL import Image
from scipy import ndimage

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PLATE = os.path.join(ROOT, 'public', 'assets', 'backgrounds', 'courtyard.png')
OUT   = os.path.join(ROOT, 'src', 'data', 'courtyard-lights.ts')

# Radii are in WORLD pixels (the map is 1056 x 864), not plate pixels — a candle
# flame is a few pixels of paint but throws light several tiles wide.
WARM   = dict(radius=165, color=(255, 188, 112), intensity=1.00, flicker=0.34, kind='candle')
VIOLET = dict(radius=250, color=(172,  92, 255), intensity=0.78, flicker=0.13, kind='rift')

def find(mask, min_px, merge_px, w, h):
    """
    Blob centroids, largest first, with nearby blobs merged into one source.

    Merging matters: a painted flame reads as two blobs, a hot core and the
    glow around it, and without merging every candle would get two lights
    stacked on it. The third value returned is the blob's pixel count, which
    the caller uses to scale intensity — a bigger flame throws more light.
    """
    lbl, n = ndimage.label(mask)
    hits = []
    for i in range(1, n + 1):
        m = lbl == i
        count = int(m.sum())
        if count < min_px:
            continue
        ys, xs = np.where(m)
        hits.append((count, float(xs.mean()), float(ys.mean())))
    hits.sort(key=lambda t: -t[0])

    kept = []
    for count, x, y in hits:
        if any((x - kx) ** 2 + (y - ky) ** 2 < merge_px ** 2 for _, kx, ky in kept):
            continue
        kept.append((count, x, y))
    return [(x / w, y / h, c) for c, x, y in kept]

def main():
    im = Image.open(PLATE).convert('RGB')
    w, h = im.size
    a = np.array(im).astype(int)
    r, g, b = a[..., 0], a[..., 1], a[..., 2]
    lum = 0.299 * r + 0.587 * g + 0.114 * b

    # Candle flames. The threshold is deliberately generous: the first pass only
    # caught the brightest eight, all of them clustered around the fountain,
    # which left the lower courtyard with no motivated light at all. Loosening it
    # picks up the dimmer candles by the benches and signs down there.
    warm = find((lum > 112) & (r > 135) & (r > b + 40) & (g > 90), 25, 20, w, h)
    # Rift burst: saturated violet. Merged wide — it is one effect, not eight.
    violet = find((b > 140) & (r > 90) & (b > g + 60) & (r > g + 20), 600, 160, w, h)

    def scaled(u, v, px, base, lo, hi):
        """Bigger painted flame -> brighter light."""
        d = dict(base)
        d['intensity'] = round(min(hi, max(lo, base['intensity'] * (0.55 + px / 170))), 3)
        d.update(u=round(u, 4), v=round(v, 4))
        return d

    lights = [scaled(u, v, px, WARM, 0.52, 1.0) for u, v, px in warm]
    lights += [scaled(u, v, px, VIOLET, 0.55, 0.85) for u, v, px in violet]
    # The fountain is a broad wash rather than a bright core, so detection is
    # unreliable — it is authored, at the same focal point the engine anchors the
    # plate on, which is by definition where the painted fountain sits.
    lights.append(dict(u=0.5, v=0.335, radius=330, color=(126, 168, 255),
                       intensity=0.85, flicker=0.07, kind='fountain'))

    body = ',\n'.join(
        f"  {{ u: {l['u']}, v: {l['v']}, radius: {l['radius']}, "
        f"color: [{l['color'][0]}, {l['color'][1]}, {l['color'][2]}], "
        f"intensity: {l['intensity']}, flicker: {l['flicker']}, kind: '{l['kind']}' }}"
        for l in lights)

    with open(OUT, 'w', encoding='utf-8', newline='\n') as f:
        f.write(f'''// GENERATED by tools/bake-lights.py — do not edit by hand.
// Light sources read out of the painted courtyard plate. `u`/`v` are normalised
// plate coordinates; the engine maps them through the same transform it uses to
// draw the plate, so a light always sits on the flame that was painted for it.
// `radius` is in world pixels (the map is 1056 x 864).

import type {{ BakedLight }} from '../game/Lighting';

export const COURTYARD_LIGHTS: BakedLight[] = [
{body},
];
''')
    counts = {}
    for l in lights:
        counts[l['kind']] = counts.get(l['kind'], 0) + 1
    print(f'  baked {len(lights)} lights -> src/data/courtyard-lights.ts')
    for k, v in counts.items():
        print(f'    {v:>2} x {k}')

if __name__ == '__main__':
    main()
